language: node_js
node_js:
- 6.10.3
before_install:
- openssl aes-256-cbc -K $encrypted_b47eb4726dfc_key -iv $encrypted_b47eb4726dfc_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- npm install
script:
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
- sls deploy -v -s $TRAVIS_BRANCH
