language: node_js
node_js:
- 6.10.3
branches:
  only:
    - prod
    - dev
before_install:
- openssl version
- openssl aes-256-cbc -K $encrypted_b47eb4726dfc_key -iv $encrypted_b47eb4726dfc_iv -in secrets.tar.enc -out secrets.tar -d
- ls -al
- tar xvf secrets.tar
install:
- npm install
script:
- npm test
after_success:
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sls deploy -v -s $TRAVIS_BRANCHT ; fi'
