version: 0.2

env:
  variables:
    stage: "prod"
  parameter-store:
    config_yml: "office-maker-api-config-prod"
    pubkey: "office-maker-api-authorizer-pubkey"

phases:
  install:
    commands:
      - echo ${config_yml} >> config.yml
      - echo -e "${pubkey}" >> ./functions/authorizer/pubkey.pem
      - npm install
      - cd functions/authorizer/ && npm install && cd -
  build:
    commands:
      - npm run test
  post_build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/master" ]; then
        ./node_modules/.bin/sls deploy -s ${stage}
      fi;

