version: 0.2

env:
  variables:
    stage: 'stg'
    JWT_BUCKET: 'office-maker-account-storage-stg'
    JWT_KEY: 'role/office-maker-stg-ap-northeast-1-lambdaRole/token'
  parameter-store:
    config_yml: 'office-maker-api-config-stg'

phases:
  install:
    runtime-versions:
      java: openjdk8
      nodejs: 8
    commands:
      - apt-get update && apt-get install -y lsof
      - echo ${config_yml} >> config.yml
      - npm i -g npm@latest
      - npm ci
      - cd functions/authorizer/ && npm ci && cd -
      - cd functions/appsyncAuthorizer/ && npm ci && cd -
      - cd common && npm ci && cd -
      - npx sls dynamodb install
  pre_build:
    commands:
      - npm run test:start
      - export STAGE_NAME="test-$(date +%s)"
      - npx sls deploy -s ${STAGE_NAME}
  build:
    commands: |
      OUTPUT=$(aws cloudformation describe-stacks --stack-name office-maker-test-1562298520 --region ap-northeast-1 | jq '.Stacks[0].Outputs') \
      STACK_NAME="office-maker-${STAGE_NAME}" \
      npm run test:integration && \
      echo '*** Test succeeded ***'

      if [ $? = 0 && "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/release" ]; \
        then echo 'Deploying to staging environment......'; \
        ./node_modules/.bin/sls deploy -s ${stage} \
      fi;

      export BUILD_STATUS="$?"
  post_build:
    commands:
      - npx sls remove -s ${STAGE_NAME} && exit ${BUILD_STATUS}

cache:
  paths:
    - '~/.npm/**/*'
