version: 0.2

env:
  variables:
    stage: "prod"
  parameter-store:
    config_yml: "office-maker-api-config-prod"
    pubkey: "office-maker-api-authorizer-pubkey"

phases:
  install:
    commands:
      - echo ${config_yml} >> config.yml
      - echo "${pubkey}" >> ./functions/authorizer/pubkey.pem
      - npm i -g npm@latest
      - npm ci
      - cd functions/authorizer/ && npm ci && cd -
      - cd common && npm ci && cd -
  build:
    commands:
      - npm run test
  post_build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/master" ]; then
        ./node_modules/.bin/sls deploy -s ${stage}
      fi;

